# USED FOR TESTING ON LOCAL MACHINE
# WILL START KAFKA AND ZOOKEEPER AND CREATE TWO DEFAULT TOPICS:
# TRANSACTION_TOPIC AND TRANSACTION_ERROR_TOPIC
#
# TO RUN: docker-compose up -d
#
# FOR MORE INFORMATION SEE THE README.md FILE IN THE ROOT OF THIS PROJECT
version: '2'
services:
  zookeeper:
    image: wurstmeister/zookeeper
    ports:
      - "2181:2181"
  kafka:
    image: wurstmeister/kafka
    ports:
      - "9092:9092"
    environment:
      KAFKA_ADVERTISED_HOST_NAME: "localhost"
      KAFKA_CREATE_TOPICS: "transaction.errors:1:1"
      # ENABLE LARGE MESSAGES IN KAFKA
      KAFKA_FETCH_MAX_BYTES: 5048576
      KAFKA_MESSAGE_MAX_BYTES: 5048576
      KAFKA_MAX_MESSAGE_BYTES: 5048576
      KAFKA_MAX_REQUEST_SIZE: 5048576
      KAFKA_CONSUMER_MAX_REQUEST_SIZE: 5048576
      KAFKA_REPLICA_FETCH_MAX_BYTES: 5048576
      KAFKA_PRODUCER_MAX_REQUEST_SIZE: 5048576
      KAFKA_CONSUMER_MAX_PARTITION_FETCH_BYTES: 5048576
      KAFKA_ZOOKEEPER_CONNECT: "zookeeper:2181"
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
